name: Run Scraper

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install poetry==1.3.1
          poetry install

      - name: Build app
        run: poetry build

      - name: Run Scraper
        run: |
          cd ncbi-scraper
          poetry run python main.py

      - name: Store json artifact in GitHub
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ./publications_dump.json
          retention-days: 1
          if-no-files-found: error

      - name: Store pdf artifact in GitHub
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ./ncbi-scraper/pmc
          retention-days: 1
          if-no-files-found: error
